### ISSUE TITLE
Implement sneaker image upload

### ISSUE THREAD

**Issue by jonathannicolasdev** [jonathannicolasdev/sneakergram-server#4]
Create post new sneaker endpoint that includes upload:

```http
POST /sneakers
```

We can use `multer` package for the upload functionality/middleware.

After the upload is done, get the file name or URL.

The URL can be used in the sneakers data.

```json
{
   "id": 0,
   "name": "",
   "imageUrl": "/uploads/sneaker-name.jpg"
}
```

Reference: 500px upload feature

**Comment by mhaidarh** [comment]
Notes, you have to specify the domain in the `.env` as well.

Development:

```
DOMAIN=http://localhost:8000
```

Production:

```
DOMAIN=http://api.sneakergram.com
```
